added Windows to INSTALL file

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -2,7 +2,11 @@
 
 # Function to install software on Ubuntu
 install_on_ubuntu() {
-  set -e # Exit immediately if a command exits with a non-zero status.
+  set -e # Exit immediately if a command exits with a non-zero status
+
+  # Save the current directory
+  local current_dir
+  current_dir=$(pwd)
 
   echo "Starting the installation process on Ubuntu..."
 
@@ -23,70 +27,76 @@ install_on_ubuntu() {
   echo "Installing Eigen..."
   sudo apt-get install -y libeigen3-dev
 
-  # Set Gurobi environment variable
+  # Prepare to install Gurobi
+  echo "Downloading and installing Gurobi..."
+  cd /opt
+  sudo wget https://packages.gurobi.com/10.0/gurobi10.0.3_linux64.tar.gz
+  sudo tar -xvf gurobi10.0.3_linux64.tar.gz
+  sudo rm gurobi10.0.3_linux64.tar.gz
   export GUROBI_HOME="/opt/gurobi/linux64"
   export PATH="${PATH}:${GUROBI_HOME}/bin"
   export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GUROBI_HOME}/lib"
-  echo "GUROBI_HOME: $GUROBI_HOME"
-  echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
-
-  # Download and install Gurobi
-  echo "Downloading and installing Gurobi..."
-  wget https://packages.gurobi.com/10.0/gurobi10.0.3_linux64.tar.gz
-  tar -xvf gurobi10.0.3_linux64.tar.gz
-  sudo mv gurobi1003 /opt
   sudo sh -c "echo '${GUROBI_HOME}/lib' > /etc/ld.so.conf.d/gurobi.conf"
   sudo ldconfig
 
   # Install SCIP
   echo "Installing SCIP..."
   sudo apt-get install -y gfortran libtbb-dev
-  curl -O https://www.scipopt.org/download/release/SCIPOptSuite-9.0.0-Linux-ubuntu22.sh
-  chmod u+x SCIPOptSuite-9.0.0-Linux-ubuntu22.sh
-  ./SCIPOptSuite-9.0.0-Linux-ubuntu22.sh --prefix=/opt/scip --exclude-subdir --skip-license
+  cd /opt
+  sudo curl -O https://www.scipopt.org/download/release/SCIPOptSuite-9.0.0-Linux-ubuntu22.sh
+  sudo chmod u+x SCIPOptSuite-9.0.0-Linux-ubuntu22.sh
+  sudo ./SCIPOptSuite-9.0.0-Linux-ubuntu22.sh --prefix=/opt/scip --exclude-subdir --skip-license
+  sudo rm SCIPOptSuite-9.0.0-Linux-ubuntu22.sh
   sudo sh -c "echo '/opt/scip/lib' > /etc/ld.so.conf.d/scip.conf"
   sudo ldconfig
 
   # Install HiGHS
   echo "Installing HiGHS..."
-  git clone https://github.com/ERGO-Code/HiGHS.git
-  cd HiGHS
-  mkdir build
+  sudo git clone https://github.com/ERGO-Code/HiGHS.git /opt/HiGHS
+  cd /opt/HiGHS
+  sudo mkdir build
   cd build
-  cmake -DFAST_BUILD=ON -DCMAKE_INSTALL_PREFIX=/opt/HiGHS ..
-  cmake --build .
+  sudo cmake -DFAST_BUILD=ON -DCMAKE_INSTALL_PREFIX=/opt/HiGHS ..
+  sudo cmake --build .
   sudo cmake --install .
   sudo sh -c "echo '/opt/HiGHS/lib' > /etc/ld.so.conf.d/highs.conf"
   sudo ldconfig
-  cd ../..
 
-  # Install COIN-OR CoinUtils and other components
-  echo "Installing COIN-OR utilities..."
+  # Install COIN-OR CoinUtils and Osi/Clp
+  echo "Installing COIN-OR CoinUtils and Osi/Clp..."
   sudo apt-get install -y coinor-libcoinutils-dev libbz2-dev liblapack-dev libopenblas-dev
-  curl -O https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
-  chmod u+x coinbrew
+  cd /opt
+  sudo curl -O https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
+  sudo chmod u+x coinbrew
   sudo ./coinbrew build CoinUtils --latest-release --skip-dependencies --prefix=/opt/coin-or --tests=none
   sudo ./coinbrew build Osi --latest-release --skip-dependencies --prefix=/opt/coin-or --tests=none --without-cplex --with-gurobi --with-gurobi-lib="-L$GUROBI_HOME/lib -lgurobi100" --with-gurobi-incdir="$GUROBI_HOME/include"
   sudo ./coinbrew build Clp --latest-release --skip-dependencies --prefix=/opt/coin-or --tests=none
+  sudo rm coinbrew
 
   # Install StOpt
   echo "Installing StOpt..."
   sudo apt-get install -y zlib1g-dev
-  git clone https://gitlab.com/stochastic-control/StOpt
-  cd StOpt
-  mkdir build
+  sudo git clone https://gitlab.com/stochastic-control/StOpt /opt/StOpt
+  cd /opt/StOpt
+  sudo mkdir build
   cd build
-  cmake -DBUILD_PYTHON=OFF -DBUILD_TEST=OFF ..
-  cmake --build .
+  sudo cmake -DBUILD_PYTHON=OFF -DBUILD_TEST=OFF ..
+  sudo cmake --build .
   sudo cmake --install . --prefix=/opt/stopt
-  cd ../..
 
   echo "Installation completed successfully on Ubuntu."
+
+  # Return to the original directory
+  cd "$current_dir"
 }
 
 # Function to install software on macOS
 install_on_macos() {
-  set -e # Exit immediately if a command exits with a non-zero status.
+  set -e # Exit immediately if a command exits with a non-zero status
+
+  # Save the current directory
+  local current_dir
+  current_dir=$(pwd)
 
   echo "Starting the installation process on macOS..."
 
@@ -114,16 +124,16 @@ install_on_macos() {
   echo "Installing Eigen..."
   brew install eigen
 
-  # Set Gurobi environment variables
+  # Download and install Gurobi
+  echo "Downloading and installing Gurobi..."
+  cd /Library
+  curl -O https://packages.gurobi.com/10.0/gurobi10.0.3_macos_universal2.pkg
+  sudo installer -pkg gurobi10.0.3_macos_universal2.pkg -target /
+  rm gurobi10.0.3_macos_universal2.pkg
   export GUROBI_HOME="/Library/gurobi1003"
   export PATH="${PATH}:${GUROBI_HOME}/bin"
   echo "GUROBI_HOME: $GUROBI_HOME"
   echo "PATH: $PATH"
-
-  # Download and install Gurobi
-  echo "Downloading and installing Gurobi..."
-  curl -O https://packages.gurobi.com/10.0/gurobi10.0.3_macos_universal2.pkg
-  sudo installer -pkg gurobi10.0.3_macos_universal2.pkg -target /
 
   # Install SCIP
   echo "Installing SCIP..."
@@ -131,11 +141,12 @@ install_on_macos() {
   curl -O https://www.scipopt.org/download/release/SCIPOptSuite-9.0.0-Darwin.sh
   chmod u+x SCIPOptSuite-9.0.0-Darwin.sh
   ./SCIPOptSuite-9.0.0-Darwin.sh --prefix=/Library/scip --exclude-subdir --skip-license
+  rm SCIPOptSuite-9.0.0-Darwin.sh
 
   # Install HiGHS
   echo "Installing HiGHS..."
-  git clone https://github.com/ERGO-Code/HiGHS.git
-  cd HiGHS
+  git clone https://github.com/ERGO-Code/HiGHS.git /Library/HiGHS
+  cd /Library/HiGHS
   mkdir build
   cd build
   cmake -DFAST_BUILD=ON -DCMAKE_INSTALL_PREFIX=/Library/HiGHS ..
@@ -143,21 +154,23 @@ install_on_macos() {
   sudo cmake --install .
   cd ../..
 
-  # Install COIN-OR CoinUtils and other components
-  echo "Installing COIN-OR utilities..."
+  # Install COIN-OR CoinUtils and Osi/Clp
+  echo "Installing COIN-OR CoinUtils and Osi/Clp..."
   brew install coinutils bz2 lapack openblas
+  cd /Library
   curl -O https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
   chmod u+x coinbrew
   ./coinbrew fetch CoinUtils --no-prompt
   ./coinbrew build CoinUtils --prefix=/Library/coin-or --no-prompt --tests=none
   ./coinbrew build Osi --prefix=/Library/coin-or --no-prompt --tests=none --without-cplex --with-gurobi --with-gurobi-lib="-L$GUROBI_HOME/lib -lgurobi100" --with-gurobi-incdir="$GUROBI_HOME/include"
   ./coinbrew build Clp --prefix=/Library/coin-or --no-prompt --tests=none
+  rm coinbrew
 
   # Install StOpt
   echo "Installing StOpt..."
   brew install zlib
-  git clone https://gitlab.com/stochastic-control/StOpt
-  cd StOpt
+  git clone https://gitlab.com/stochastic-control/StOpt /Library/StOpt
+  cd /Library/StOpt
   mkdir build
   cd build
   cmake -DBUILD_PYTHON=OFF -DBUILD_TEST=OFF ..
@@ -166,13 +179,125 @@ install_on_macos() {
   cd ../..
 
   echo "Installation completed successfully on macOS."
+
+  # Return to the original directory
+  cd "$current_dir"
+}
+
+# Function to install software on Windows
+function install_on_windows() {
+  # Save current directory
+  local current_dir
+  current_dir=$(pwd)
+
+  echo "Starting the installation process on Windows..."
+
+  # Ensure the directory for vcpkg exists and move to it
+  echo "Preparing the installation directory for vcpkg..."
+  mkdir -p /c/vcpkg
+  cd /c/vcpkg
+
+  # Install vcpkg
+  echo "Installing vcpkg..."
+  git clone https://github.com/microsoft/vcpkg.git .
+  ./bootstrap-vcpkg.bat
+
+  # Install basic requirements
+  echo "Installing basic requirements with vcpkg..."
+  ./vcpkg install cmake git --triplet x64-windows
+  ./vcpkg install zlib bzip2 pthreads getopt --triplet x64-windows
+
+  # Install Boost libraries
+  echo "Installing Boost libraries..."
+  ./vcpkg install boost boost-mpi --triplet x64-windows
+
+  # Install Eigen
+  echo "Installing Eigen..."
+  ./vcpkg install eigen3 --triplet x64-windows
+
+  # Install NetCDF
+  echo "Installing NetCDF..."
+  ./vcpkg install netcdf-cxx4 --triplet x64-windows
+
+  # Move to C:\ for other dependencies
+  echo "Moving to C:\ for downloading and installing other dependencies..."
+  cd /c/
+
+  # Download and install Gurobi
+  echo "Downloading and installing Gurobi..."
+  local gurobi_installer="Gurobi-10.0.3-win64.msi"
+  curl -LO "https://packages.gurobi.com/10.0/$gurobi_installer"
+  cmd //c start /wait msiexec /i $gurobi_installer /qn
+  rm $gurobi_installer
+
+  # Download and install SCIP
+  echo "Downloading and installing SCIP..."
+  local scip_installer="SCIPOptSuite-9.0.0-win64-VS15.exe"
+  curl -LO "https://www.scipopt.org/download.php?fname=$scip_installer"
+  cmd //c start /wait $scip_installer /SILENT
+  rm $scip_installer
+
+  # Install HiGHS
+  echo "Installing HiGHS..."
+  git clone https://github.com/ERGO-Code/HiGHS.git
+  cd HiGHS
+  mkdir build
+  cd build
+  cmake -DFAST_BUILD=ON -DCMAKE_INSTALL_PREFIX=C:/HiGHS ..
+  cmake --build .
+  cmake --install .
+  cd ../..
+
+  # Move to C:\vcpkg to install COIN-OR CoinUtils and Osi/Clp
+  printf "Moving to C:\\vcpkg for installing COIN-OR CoinUtils and Osi/Clp...\n"
+  cd /c/vcpkg
+
+  # Install COIN-OR CoinUtils
+  echo "Installing COIN-OR CoinUtils..."
+  ./vcpkg install coinutils pybind11 blas lapack --triplet x64-windows
+
+  echo "Modifying COIN-OR Osi portfile.cmake for Gurobi support..."
+  cd /c/vcpkg/ports/coin-or-osi
+
+  # Backup the original portfile.cmake just in case
+  cp portfile.cmake portfile.cmake.bak
+
+  # Use sed `s/old/new/` to replace the configuration line
+  sed -i 's/--with-gurobi/&\
+          --with-gurobi-lib=C:\\\/gurobi1003\\\/win64\\\/lib\\\/gurobi100.lib\
+          --with-gurobi-incdir=C:\\\/gurobi1003\\\/win64\\\/include\
+          --with-gurobi-cflags=-IC:\\\/gurobi1003\\\/win64\\\/include\
+          --with-gurobi-lflags=C:\\\/gurobi1003\\\/win64\\\/lib\\\/gurobi100.lib/' portfile.cmake
+
+  echo "COIN-OR Osi portfile modified for Gurobi support."
+
+  # Install COIN-OR Osi/Clp
+  echo "Installing COIN-OR Osi with Gurobi support..."
+  cd /c/vcpkg
+  ./vcpkg install blas lapack --triplet x64-windows
+  ./vcpkg install coin-or-osi coin-or-clp glpk pybind11 --triplet x64-windows
+
+  # Setup vcpkg for StOpt installation
+  echo "Setting up vcpkg for StOpt installation..."
+  cd /c/
+  git clone https://gitlab.com/stochastic-control/vcpkg-registry
+  cd /c/vcpkg
+
+  # Install StOpt using custom vcpkg registry
+  echo "Installing StOpt..."
+  ./vcpkg install stopt --overlay-ports=/c/vcpkg/vcpkg-registry/ports/stopt --triplet x64-windows
+  rm -rf /c/vcpkg-registry
+
+  echo "Installation completed successfully on Windows."
+
+  # Return to the original directory
+  cd "$current_dir"
 }
 
 # Detect operating system and execute the appropriate installation function
 OS="$(uname)"
 case "$OS" in
 "Linux")
-  # Check if it's Ubuntu
   if [ -f /etc/lsb-release ]; then
     . /etc/lsb-release
     if [ "$DISTRIB_ID" = "Ubuntu" ]; then
@@ -187,7 +312,23 @@ case "$OS" in
 "Darwin")
   install_on_macos
   ;;
+"Windows")
+  install_on_windows
+  ;;
 *)
   echo "This script does not support the detected operating system."
   ;;
 esac
+
+# Compile SMSpp
+echo "Compiling SMSpp..."
+mkdir -p build
+cd build
+cmake ..
+cmake --build . --config Release
+if [[ "$OS" != "Windows" ]]; then
+  sudo cmake --install .
+else
+  cmake --install .
+fi
+cd ..
